main-server/accounts/urls.py
from django.urls import path
from . import views
from django.contrib.auth.views import LogoutView

app_name = 'accounts'

urlpatterns = [
    path('signup/',views.SignUp.as_view(),name='signup'),
    path('login/',views.Login.as_view(),name = 'login'),
    path('logout/',LogoutView.as_view(),name='logout'),
]

main-server/videocall/urls.py
from django.urls import path
from . import views

app_name = 'videocall'

urlpatterns = [
    path('',views.VideoCall.as_view(),name = 'room')
]

main-server/accounts/models.py
from django.db import models
from django.contrib import auth
# Create your models here.

class User(auth.models.User, auth.models.PermissionsMixin):
    
    def __str__(self):
        return (self.first_name+"-"+self.username)

main-server/videocall/models.py
from django.db import models
from django.contrib.auth import get_user_model

User = get_user_model()

#Model for Storing Channel Name of Participants   
class Participant(models.Model):
    user = models.ForeignKey(User,on_delete=models.CASCADE)
    channelname = models.CharField(max_length = 250)
    
    def __str__(self):
        return self.user.username

#Model for Chat Room
class ChatRoom(models.Model):
    roomid = models.CharField(max_length=250,primary_key=True)
    admin = models.ForeignKey(User,on_delete=models.CASCADE)
    participants = models.ManyToManyField(Participant,related_name="participant",blank=True)
    
    def __str__(self):
        return self.roomid
 
    

main-server/accounts/forms.py
from django.contrib.auth import get_user_model
from django.contrib.auth.forms import UserCreationForm

class UserCreateForm(UserCreationForm):
    class Meta:
        model = get_user_model()
        fields = ['username','first_name','last_name','password1','password2']
        
    def __init__(self,*args,**kwargs):
        super().__init__(*args,**kwargs)
        self.fields['username'].label = "Email"
        self.fields['password1'].label = "Password"
        self.fields['password2'].label = "Re-enter Password"
        self.fields['first_name'].required = True
        self.fields['first_name'].label = "First Name"
        self.fields['last_name'].label = "Last Name"
        
    def save(self,commit=True):
        user = super(UserCreateForm,self).save(commit=False)
        user.email = user.username
        if commit:
            user.save()
        return user
    

main-server/accounts/views.py
from django.urls import reverse_lazy
from django.views.generic.edit import CreateView
from django.contrib.auth.views import LoginView, LogoutView
from . import forms

class SignUp(CreateView):
    form_class = forms.UserCreateForm
    success_url = reverse_lazy('accounts:login')
    template_name = 'registration/signup2.html'
    
    def get_context_data(self,*args,**kwargs):
        context =  super().get_context_data(*args,**kwargs)
        context['form'].fields['username'].help_text = None
        context['form'].fields['password1'].help_text = None
        context['form'].fields['password2'].help_text = None

        context['form'].fields['username'].label = 'Пошта'
        context['form'].fields['first_name'].label = 'Ім\'я'
        context['form'].fields['last_name'].label = 'Прізвище'
        context['form'].fields['password1'].label = 'Пароль'
        context['form'].fields['password2'].label = 'Введіть пароль ще раз'

        return context
    
class Login(LoginView):
    template_name = 'registration/login2.html'
    
    def get_context_data(self,*args,**kwargs):
        context =  super().get_context_data(*args,**kwargs)
        context['form'].fields['username'].label = 'Пошта'
        context['form'].fields['password'].label = 'Пароль'
        return context

    

main-server/videocall/views.py
from django.shortcuts import render
from django.views.generic.base import TemplateView
from django.contrib.auth.mixins import LoginRequiredMixin
# Create your views here.

class VideoCall(LoginRequiredMixin,TemplateView):
    template_name = "videocall/videocall2.html"
    
    

main-server/videochat/views.py
from django.contrib.auth.decorators import login_required
from django.http import JsonResponse
from videocall.models import ChatRoom
from django.shortcuts import redirect

@login_required(redirect_field_name=None)
def HomePage(request):
    from django.shortcuts import render

    return render(request, "home2.html")


#Create a Room
@login_required
def CreateRoomLink(request):
    import uuid
    import base64
    
    if(request.method=="GET"):
        randomid = str(uuid.uuid4()) #RandomId Generator
        randomid_bytes = randomid.encode("ascii") #
        randomid_bytes = base64.b64encode(randomid_bytes)
        randomid = randomid_bytes.decode("ascii")
    
    try:
        ChatRoom.objects.create(pk = randomid,admin = request.user)
        return JsonResponse({'valid':1,'roomid':randomid},status=200)
    except Exception as e:
        print(e)
        return JsonResponse({'valid':0,'message':"Sorry!! Click Create-Room Again!!"},status=200)
    

@login_required
def CheckRoom(request,*args,**kwargs):
    room_id = kwargs.get('room_id',None)
    try:
        if(room_id and ChatRoom.objects.get(pk=room_id)):
            return JsonResponse({'valid':1},status=200)
    except:
        return JsonResponse({'valid':0},status=200)
    
    return True

main-server/templates/base.html
<!DOCTYPE html>
{% load static %}
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>{% block title %}{% endblock %}</title>
    
    <!-- Bootstrap CSS Bundle -->
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.0.2/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-EVSTQN3/azprG1Anm3QDgpJLIm9Nao0Yz1ztcQTwFspd3yD65VohhpuuCOmLASjC" crossorigin="anonymous">
    
    <!-- Other CSS links -->
    <link rel="stylesheet" href="{% static 'css/base.css' %}">
    {% block csslinks %}{% endblock %}
</head>
<body>
    <!-- Nav Bar -->
    <nav class="navigation">
        <div class="container-fluid">
            <div class="row">
                <div class="logo col-sm-3">
                    <a href="#">Waves</a>
                </div>
                <div id="mainListDiv" class="main_list col-sm-9">
                    <ul class="navigationlinks">
                        <li style="color:white">
                            <a id="hour"></a>
                            <a>:</a>
                            <a id="mins"></a>
                            <a id="meridian"></a>
                            <a>|</a>
                            <a id="date"></a>
                            <a id="month"></a>
                            <a id="year"></a>
                        </li>
                        {% if user.is_authenticated %}
                            <li><a>Hi! {{user.first_name}}</a></li>
                            <li><a href="{% url 'accounts:logout' %}">LogOut</a></li>
                        {% endif %}
                    </ul>
                </div>
                <span class="navigationTrigger">
                    <i></i>
                    <i></i>
                    <i></i>
                </span>
            </div>
        </div>
    </nav>

    <section class="main">
        <!-- Content -->
        {% block content %}{% endblock %}
    </section>
    
    <footer>
        <p>&copy;Made by Saswat Das</p>
    </footer>

</body>

<!-- Bootstrap JS Bundle -->
<script src="https://cdn.jsdelivr.net/npm/bootstrap@5.0.2/dist/js/bootstrap.bundle.min.js" integrity="sha384-MrcW6ZMFYlzcLA8Nl+NtUVF0sA7MsXsP1UyJoMp4YLEuNSfAP+JcXn/tWtIaxVXM" crossorigin="anonymous"></script>
<!-- Jquery needed -->
<script src="https://ajax.googleapis.com/ajax/libs/jquery/3.1.1/jquery.min.js"></script>

<!-- Function used to shrink nav bar removing paddings and adding a light blue background -->
<script>
    //Update clock every minute
    var hour = document.getElementById('hour');
    var mins = document.getElementById('mins');
    var meridian = document.getElementById('meridian');
    var date = document.getElementById('date');
    var month = document.getElementById('month');
    var year = document.getElementById('year');
    const months = ["Jan", "Feb", "Mar", "Apr", "May", "June", "July", "Aug", "Sept", "Oct", "Nov", "Dec"];
    
    function clock()
    {
        var d = new Date();
        var hour_ = d.getHours();
        var mins_ = d.getMinutes();
        var date_ = d.getDate();
        var month_ = d.getMonth();
        var year_ = d.getFullYear();

        if(hour_ >= 12){
            meridian.innerHTML = 'PM';
        }
        else{
            meridian.innerHTML = 'AM';
        }
        if(hour_ === 0){hour_ = 12;}
        if(hour_ > 12){hour_-=12;}

        if(hour_>=1 && hour_<=9)
        {
            hour_ = '0'+hour_;
        }
        if(mins_>=0 && mins_<=9)
        {
            mins_ = '0'+mins_;
        }
        
        //Initialise
        hour.innerHTML = hour_;
        mins.innerHTML = mins_;
        date.innerHTML = date_;
        month.innerHTML = months[month_];
        year.innerHTML = year_;
    }
    clock();
    setInterval(clock,1000);

    //trigger function
    $('.navigationTrigger').click(function () {
        $(this).toggleClass('active');
        //console.log("Clicked menu");
        $("#mainListDiv").toggleClass("show_list");
        $("#mainListDiv").fadeIn();
    
    });

    // func used to shrink nav bar removing paddings and adding a light blue background 
    $(window).scroll(function() {
        if ($(document).scrollTop() > 50) {
            $('.navigation').addClass('affix');
            //console.log("OK");
        } else {
            $('.navigation').removeClass('affix');
        }
    });

    
    
</script>
<!-- Other JS links -->
{% block jslinks %}{% endblock %}

</html>

main-server/templates/home.html
{% extends "base.html" %}
{% load static %}
{% block csslinks %}
    <link rel="stylesheet" href="{% static 'css/home.css' %}">
    <link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/bootstrap-icons@1.3.0/font/bootstrap-icons.css">
{% endblock %}
{% block content %}
    <div id="createroom" class="container-fluid" style="background-color:aliceblue">
        <div class="row">
            <div class="col-sm-5">
                <div id="link-generation">
                    {% if user.is_authenticated %}
                        <div id="message">
                            <h1>Greetings!! Generate a link for videochat room by clicking below.</h1>
                            <br>
                            <p>Talk to your friends and share memories.</p>
                        </div>
                        <div id="link">
                            <button id="create-room" class="btn btn-primary" data-bs-toggle="modal" data-bs-target="#linkmodal">Create ChatRoom</button>
                            <input type="text" id="paste-link" placeholder="Paste link or roomcode">
                            <a href='' id="join" class="btn btn-outline-primary">Join</a>

                            <!-- Modal to show the link -->
                            <div class="modal fade" id="linkmodal" data-bs-backdrop="static" data-bs-keyboard="false" tabindex="-1" aria-labelledby="staticBackdropLabel" aria-hidden="true">
                                <div class="modal-dialog modal-dialog-centered">
                                  <div class="modal-content">
                                    <div class="modal-header">
                                      <h5 class="modal-title" id="linkmodalLabel" style="font-size:1.5rem;"><strong> Here 's the link to your chatroom</strong></h5>
                                      <button type="button" class="btn-close" data-bs-dismiss="modal" aria-label="Close"></button>
                                    </div>
                                    <div class="modal-body" style="font-size:2rem;">
                                      <p>Copy the link and send it to the people you want to chat with!!😊😊</p>
                                      <div style="background-color:#f1f3f4;">
                                        <div class="input-group mb-3">
                                            <input id="chatroomlink" disabled type="url" class="form-control" placeholder="ChatRoom Link" aria-label="ChatRoom-Link" value="" style="font-size:2rem;text-align:center;">
                                            <div class="input-group-append">
                                              <button id="copytoclipboard" type="button" class="btn"><i class="bi bi-clipboard" style="font-size: 2.5rem"></i></button>
                                            </div>
                                          </div>
                                        </div>
                                    </div>
                                  </div>
                                </div>
                              </div>
                        </div>
                    {% else %}
                        <div id="auth_message">
                            <h1>Greetings!! Welcome to Waves.</h1>
                            <br>
                            <p>Login/SignUp below to create chatrooms and meet your friends.</p>
                        </div>
                        <div id="authentication">
                            <a href="{% url 'accounts:login' %}" class="btn btn-primary user_auth">Login</a>
                            <a href="{% url 'accounts:signup' %}" class="btn btn-primary user_auth">SignUp</a>
                        </div>
                    {% endif %}
                            
                </div>
            </div>
            <div class="col-sm-7">
                <img id="rightside-img" src="{% static 'image/videocall.png' %}" alt="VideoCall-Image">
            </div>
        </div>
    </div>
{% endblock %}
{% block jslinks %}
    <script src="{% static 'js/home.js' %}"></script>
{% endblock %}

main-server/videocall/templates/videocall/videocall.html
<!DOCTYPE html>
{% load static %}
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Waves</title>
    <link rel="stylesheet" href="{% static 'css/videocall/videocall.css' %}">
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.0.2/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-EVSTQN3/azprG1Anm3QDgpJLIm9Nao0Yz1ztcQTwFspd3yD65VohhpuuCOmLASjC" crossorigin="anonymous">
    <link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/bootstrap-icons@1.3.0/font/bootstrap-icons.css">
    <style>
        .announce{
            text-align:center; 
            background-color: aliceblue;
            padding:2rem;
          }
        
          .announce > a {
            font-size:2.5rem;
            margin:2rem;
            margin-bottom:1rem;
          }

          .announce p ,.announce h1 {
            font-size:3rem;
          }
    </style>
</head>
<body>
    <div class="main">
        {{ view.kwargs.room_id|json_script:"room-id" }}
        {{ request.user.username|json_script:"username" }}

        <!-- Ready to enter room -->
        <div id="ready-room" class="container-fluid">
            <div class="preview-video row">
                <div class="videosettings col-sm-12 col-md-7">
                    <video id="localVideo" autoplay playsinline></video>
                    <div id="settings">
                        <div>
                            <button class="audio-toggle" class="btn"><i class="bi bi-mic-fill"></i></button>
                            <button class="video-toggle" class="btn"><i class="bi bi-camera-video-fill"></i></button>
                        </div>
                    </div>
                </div>
                <div class="joinsettings col-sm-12 col-md-5" style="margin:auto;padding-top:1rem;text-align:center;">
                    <p style="color:aliceblue;margin:20px;font-size:3rem;">Meet your friends!!😀😀😀</p>
                    <button id="Join-Room" disabled class="btn btn-light" style="font-size:2.5rem;margin:10px;">Join Room</button>
                </div>
            </div>
        </div>

        <!-- Room ready -->
        <div id="room" style="display:none;">
            <div class="videos grid-container" id="videos">
                <div class="videotrack grid-item">
                    <video id="localVideo-joined" autoplay playsinline></video>
                    <!-- <span class="aboutuser">
                        <p>Name</p>
                    <span> -->
                </div>
            </div>
            <div id="controls">
                <button class="audio-toggle" class="btn"><i class="bi bi-mic-fill"></i></button>
                <button class="video-toggle" class="btn"><i class="bi bi-camera-video-fill"></i></button>
                <button id="leave-room" class="btn" style="background-color:red;margin-bottom:0.7rem;"><i class="bi bi-x-circle-fill"></i></button>
            </div>
        </div>

        <!-- Return to room -->
        <div id="return-room" style="display:none;">
            <div class="return-to-room-options">
                <h1 style="font-size:3rem;">Return to the ChatRoom!!✔ <br><br> Your friends may be waiting for you!!!👨‍👦‍👦😊</h1>
                <a href="{% url 'videocall:room' view.kwargs.room_id %}"><button id="returnroom" class="btn btn-primary">Return Room</button></a>
                <a href="{% url 'home' %}"><button id="home" class="btn btn-dark">Return HomePage</button></a>
            </div>
        </div>

        <!-- Show error message if room is not valid -->
        <div id="roomnotfound" style="padding:20vh 10vw;display:none;">
            <div class="announce">
                <h1>
                    Check your ChatRoom Code!!😕😕
                </h1>
                <p>
                    Make sure you entered the correct meeting code in the URL.😊😊
                </p>
                <a href="{% url 'home' %}" class="btn btn-primary">Go to HomePage</a>
            </div>
        </div>
    </div>
</body>
</html>

{% block content %}
    

    
{% endblock %}
{% block jslinks %}
    <script src="https://ajax.googleapis.com/ajax/libs/jquery/3.1.1/jquery.min.js"></script>
    <script src="{% static 'js/videocall/videocall.js' %}"></script>
{% endblock %}

main-server/videocall/templates/videocall/videocall2.html
<!DOCTYPE html>
{% load static %}
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>Super Platform</title>

    <link rel="stylesheet" href="{% static 'css/videocall/videocall2.css' %}">
{#    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.0.2/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-EVSTQN3/azprG1Anm3QDgpJLIm9Nao0Yz1ztcQTwFspd3yD65VohhpuuCOmLASjC" crossorigin="anonymous">#}
    <link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/bootstrap-icons@1.3.0/font/bootstrap-icons.css">

</head>
<body>
    <div class="main">
        {{ view.kwargs.room_id|json_script:"room-id" }}
        {{ request.user.username|json_script:"username" }}

        <!-- Ready to enter room -->
        <div id="ready-room" class="container-fluid">
            <div class="preview-video row">
                <div class="videosettings col-sm-12 col-md-7">
                    <video id="localVideo" autoplay playsinline></video>
                    <div id="settings">
                        <div>
                            <button class="audio-toggle" class="btn"><i class="bi bi-mic-fill"></i></button>
                            <button class="video-toggle" class="btn"><i class="bi bi-camera-video-fill"></i></button>
                        </div>
                    </div>
                </div>
                <div class="side-menu">
                    <p>Готові приєднатися?</p>
                    <button id="Join-Room" disabled class="btn btn-light">Увійти</button>
                    <a href="/" id="Leave-back" class="btn btn-light">Вийти</a>
                </div>
            </div>
        </div>

        <!-- Room ready -->
        <div id="room" style="display:none;">
            <div class="videotrack-local">
                    <video id="localVideo-joined" autoplay playsinline></video>
                    <!-- <span class="aboutuser">
                        <p>Name</p>
                    <span> -->
                </div>
            <div class="container-main">
                <div class="videos grid-container" id="videos">

                </div>
                <div id="controls">
                    <button class="audio-toggle" class="btn"><i class="bi bi-mic-fill"></i></button>
                    <button class="video-toggle" class="btn"><i class="bi bi-camera-video-fill"></i></button>
                    <button id="leave-room" class="btn" style="background-color:red;margin-bottom:0.7rem;"><i class="bi bi-x-circle-fill"></i></button>
                </div>
            </div>
        </div>

        <!-- Return to room -->
        <div id="return-room" style="display:none;">
            <div class="return-to-room-options">
                <h1 style="font-size:3rem;">Return to the ChatRoom!!✔ <br><br> Your friends may be waiting for you!!!👨‍👦‍👦😊</h1>
                <a href="{% url 'videocall:room' view.kwargs.room_id %}"><button id="returnroom" class="btn btn-primary">Return Room</button></a>
                <a href="{% url 'home' %}"><button id="home" class="btn btn-dark">Return HomePage</button></a>
            </div>
        </div>

        <!-- Show error message if room is not valid -->
        <div id="roomnotfound" style="padding:20vh 10vw;display:none;">
            <div class="announce">
                <h1>
                    Check your ChatRoom Code!!😕😕
                </h1>
                <p>
                    Make sure you entered the correct meeting code in the URL.😊😊
                </p>
                <a href="{% url 'home' %}" class="btn btn-primary">Go to HomePage</a>
            </div>
        </div>
    </div>

</body>
</html>

{% block jslinks %}
    <script src="https://ajax.googleapis.com/ajax/libs/jquery/3.1.1/jquery.min.js"></script>
    <script src="https://cdnjs.cloudflare.com/ajax/libs/socket.io/4.7.2/socket.io.js"></script>
    <script src="{% static 'js/videocall/videocall.js' %}"></script>
{% endblock %}